# Generated by Django 2.2.1 on 2019-05-04 00:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('person_name', models.CharField(blank=True, max_length=50, null=True)),
                ('person_attributes', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
